[build]
  publish = "public"
  command = "npm install"

[[redirects]]
  from = "/api/*"
  to = "https://prime-elite-store-ai.vercel.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
